### ISSUE TITLE
Buttons visible on read-only pads

### ISSUE THREAD

**Issue by thmo** [ether/ep_align#16]
For the read-only version of a pad, normally all formatting buttons are not visible. The four buttons of the ep_align plugin remain visible however.

**Comment by thmo** [comment]
Using the buttons changes the displayed version of the read-only pad, but the changes are rejected with
```
[WARN] message - Dropped message, COLLABROOM for readonly pad
```
and vanish after reloading the read-only pad.

Sometimes however, fiddling with those buttons in the read-only pad causes the pad to loose its connection to the server.

**Comment by ovari** [comment]
Can the buttons be shown and disabled (greyed out)? The image below has the first 3 buttons enabled and the remaining buttons disabled.

![image](https://user-images.githubusercontent.com/17465872/88885769-7b9ebe00-d27c-11ea-9baf-d24be0dcb424.png)

What do you think?

Thank you

**Comment by JohnMcLear** [comment]
it's better to just not show them on RO version.  See how ep_headings2 does it

**Comment by rfcmaXi** [comment]
I would also like to see this adaptation and prioritize it highly.

**Comment by JohnMcLear** [comment]
@rfcmaXi donate at https://etherpad.org and I will prioritize.

**Comment by JohnMcLear** [comment]
cc @ilmartyrk - re buttons

**Comment by JohnMcLear** [comment]
seems fixed :)
