### ISSUE TITLE
Are the locales working?

### ISSUE THREAD

**Issue by ovari** [ether/ep_align#22]
In the `de` and `fr` (image shown below) locale at https://video.etherpad.com/, the alignment buttons are incorrectly showing in `en`.

![image](https://user-images.githubusercontent.com/17465872/89019443-a4987f00-d360-11ea-9768-c140f680a31d.png)

Are corrections required at https://github.com/JohnMcLear/ep_align/blob/master/templates/editbarButtons.ejs#L4-L5 in the `title` property?

Thank you

**Comment by woeterman94** [comment]
I think https://github.com/ether/ep_align/pull/31 should fix this.
