### ISSUE TITLE
Couldn't find translation key ep_align_justify

### ISSUE THREAD

**Issue by woeterman94** [ether/ep_align#28]
I have a locale file but I keep getting this warning in console.

![image](https://user-images.githubusercontent.com/5755057/96858805-07318080-1461-11eb-9b5f-0d45197705ce.png)

**Comment by woeterman94** [comment]
same question as 22
Should the translation file be updated to `ep_align_justify` instead of `ep_align.justify` ? 
Or is something else wrong?

**Comment by woeterman94** [comment]
I was able to translate the value of the buttons but not the title or area-label.

![image](https://user-images.githubusercontent.com/5755057/96862223-790bc900-1465-11eb-875b-f8a793639464.png)


I think to be able to translate these properties I need something like this:

```
    orderedlist: {
      command: "insertorderedlist",
      localizationId: "pad.toolbar.ol.title",
      class: "buttonicon buttonicon-insertorderedlist"
    },

    unorderedlist: {
      command: "insertunorderedlist",
      localizationId: "pad.toolbar.ul.title",
      class: "buttonicon buttonicon-insertunorderedlist"
    },
```

any ideas?

**Comment by JohnMcLear** [comment]
``ep_align.justify`` would be correct.  The EJS / HTML file is wrong and needs fixing.

**Comment by woeterman94** [comment]
I'm having trouble translation the "title" and "area-label" properties. Any ideas?

**Comment by JohnMcLear** [comment]
will take a look

**Comment by JohnMcLear** [comment]
https://github.com/ether/ep_align/commit/c8baa218c89711b118756054cfc8d4792b37d16c is the beginning of the fix, still need to do Aria and Title.

**Comment by JohnMcLear** [comment]
yea tbh I'm not sure why trans of title and aria aren't working and I can't spend any more time on this at the moment.

**Comment by woeterman94** [comment]
Ok no problem. I was looking at the etherpad repo for some examples and I stumbled upon the example above.

**Comment by JohnMcLear** [comment]
@ilmartyrk fixed this on ep_comments: https://github.com/ether/ep_comments/pull/130 

and test: https://github.com/ether/ep_font_color/commit/52bd930f806d815454e0b737132910958eb86c4a

If you ask nicely he might fix this too ;)  cc @woeterman94 cc @ilmartyrk

**Comment by JohnMcLear** [comment]
Pretty sure this is already fixed actually..  Lemme know if not will re-open
