### ISSUE TITLE
buttons don't show up

### ISSUE THREAD

**Issue by tinkerd** [ether/ep_align#32]
with etherpad 1.8.6 (2c8769a) the buttons aren't showing up at all. 

get the following console errors:
Failed to load 'ep_align/static/js/index' for 'ep_align/main/client_hooks/aceEditEvent': Not a function
Failed to load 'ep_align/static/js/index' for 'ep_align/main/client_hooks/postToolbarInit': Not a function
Failed to load 'ep_align/static/js/index' for 'ep_align/main/client_hooks/aceDomLineProcessLineAttributes': Not a function

**Comment by JohnMcLear** [comment]
Try clear cache

**Comment by tinkerd** [comment]
I tried:
	npm cache clean --force
and doing a hard refresh in the browser

Is there a different cache?

thanks
-Luke
npm cache clean --force

**Comment by JohnMcLear** [comment]
Okay will take a look.

**Comment by tinkerd** [comment]
Hi John,

looks like I'm using several of you plugins.

I'm also having touble with cursor_trace and font_size

what sort of debugging info is helpful to you?

Thanks for the plugins - I appreciate the alternative to google docs

-Luke

**Comment by tinkerd** [comment]
Cursor_trace problem unique to Firefox btw

**Comment by JohnMcLear** [comment]
Should get time to look tomorrow

**Comment by JohnMcLear** [comment]
buttons working fine in ep_align

**Comment by JohnMcLear** [comment]
How are you installing/updating?  I did git clone...

**Comment by JohnMcLear** [comment]
I tested npm install too, totally fine, and tested w/ multiple browsers....
